---

application:
  logPath: logs
  logLevel: 7
  org:
    - name: Org1
      admin: Admin
      user: User1
    - name: Org2
      admin: Admin
      user: User1
  orderer:
    - name: Orderer
      admin: Admin
      endpoint: orderer.example.com
